### ISSUE TITLE
How do I logout?

### ISSUE THREAD

**Issue by papagno** [rheinfabrik/Heimdall.droid#38]
Removing the token from OAuth2AccessTokenStorage doesn't require the user to login again. The login activity opens and closes in a couple of seconds automatically authenticating the user again.

(I'm using the Trakt API example).

**Comment by Gi-lo** [comment]
When you remove the access token, the Android webview will still use the login data that it has cached (username/password). That is why it will automagically authenticate the user again. In order to really logout, you have to [clear the webview cache](http://stackoverflow.com/questions/28998241/how-to-clear-cookies-and-cache-of-webview-on-android-when-not-in-webview) and also (optional) [revoke the access token on the server](http://docs.trakt.apiary.io/#reference/authentication-oauth/revoke-token/revoke-an-access_token).

(I've added the logout feature)[https://github.com/rheinfabrik/Heimdall.droid/pull/39] as action menu item to the sample application :)

**Comment by papagno** [comment]
Great. Thank you very much!
